// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveLoop.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveLoop::DriveLoop(double turnAxis, double fwdAxis): Command() {
    m_turnAxis = turnAxis;
    m_fwdAxis = fwdAxis;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::tankDriveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveLoop::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveLoop::Execute() {
	m_turnAxis = Robot::oi->turnAxis();
	m_fwdAxis = Robot::oi->fwdAxis();
	channel_12 = RobotMap::catapultCatapultMotorCurrent->GetCurrent(12);
	channel_13 = RobotMap::catapultCatapultMotorCurrent->GetCurrent(13);
	channel_14 = RobotMap::catapultCatapultMotorCurrent->GetCurrent(14);
	channel_15 = RobotMap::catapultCatapultMotorCurrent->GetCurrent(15);
	voltage = RobotMap::catapultCatapultMotorCurrent->GetVoltage();
	SmartDashboard::PutNumber("turnAxis",m_turnAxis);
	SmartDashboard::PutNumber("fwdAxis",m_fwdAxis);
	SmartDashboard::PutNumber("channel 12",channel_12);
	SmartDashboard::PutNumber("channel 13",channel_13);
	SmartDashboard::PutNumber("channel 14",channel_14);
	SmartDashboard::PutNumber("channel 15",channel_15);
	SmartDashboard::PutNumber("Voltage",voltage);

	total_current = RobotMap::catapultCatapultMotorCurrent->GetCurrent(12)
			+RobotMap::catapultCatapultMotorCurrent->GetCurrent(13)
			+RobotMap::catapultCatapultMotorCurrent->GetCurrent(14)
			+RobotMap::catapultCatapultMotorCurrent->GetCurrent(15);
	SmartDashboard::PutNumber("Total Current",total_current);


	if ((voltage*lpVal)+(oldVoltage*(1-lpVal)) < 10){
		m_turnAxis *= (voltage-8)/2;
		m_fwdAxis *= (voltage-8)/2;
	}
	Robot::tankDriveTrain->arcade(m_turnAxis,m_fwdAxis);
	oldVoltage = voltage;
}

// Make this return true when this Command no longer needs to run execute()
bool DriveLoop::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void DriveLoop::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveLoop::Interrupted() {

}
