// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVELOOP_H
#define DRIVELOOP_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveLoop: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	DriveLoop(double turnAxis, double fwdAxis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();/*{
		m_turnAxis = Robot::oi->getxbox()->GetRawAxis(4);
		m_fwdAxis = Robot::oi->getxbox()->GetRawAxis(1);
		SmartDashboard::PutNumber("turnAxis",m_turnAxis);
		SmartDashboard::PutNumber("fwdAxis",m_fwdAxis);
		Robot::tankDriveTrain->arcade(m_turnAxis,m_fwdAxis);
	}*/
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	double turnAxis;
	double fwdAxis;
	double total_current;
	double max_current;
	double channel_12;
	double channel_13;
	double channel_14;
	double channel_15;
	double voltage=12;
	double oldVoltage=12;
	double lpVal = .8; // low pass value to average the voltage
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    double m_turnAxis;
    double m_fwdAxis;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
